Desktop
Blossom-Aniedi/Portfolio-Website pull request #5
Opened 2022-07-08 17:17 UTC by Blossom-Aniedi

2022-07-08 17:42 UTC, mmsesay reviewed
Hi @Blossom-Aniedi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't meet the following requirements:
 - [ ] No descriptive PR summary. It will be good to always provide a descriptive PR summary, explaining the changes that were introduced in your project. That will give other developers or visitors a brief of what you worked on.
 - [ ] The README should be descriptive also of your project. Please use this [template](https://github.com/microverseinc/readme-template/blob/master/README.md) as a guide to work on your readme. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-07-08 18:29 UTC, wuletawwonte requested changes
# Hi @Blossom-Aniedi 👋🏿👋🏿👋🏿  

Good job so far!
There are some issues that you still need to work on to go to the next project! You have only a few more steps and you are done! 💪 💪 💪 

![giphy](https://user-images.githubusercontent.com/74506933/153382064-ed760a8c-4f4a-48d6-b1f0-1aa9e5135097.gif)

## TO HIGHLIGHT: 
- Your project is professional ✔️ 
- Correct Github Flow ✔️
- Well structured files ✔️ 

## Required Changes ♻️
_Please check the comments under the review as well._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-08 18:29 UTC, wuletawwonte commented on style.css
> +    width: 1100px;
- [ ] The width of the website is wider than the width of the viewport when the viewport size is in the range 768px - 1024px. The website starts to scroll horizontally when its content is wider than the viewport. Please make sure everything fits within the size of the viewport. You can use `%` or `vw` for horizontal margins and padding as well. And please avoid giving static values in `px` for a width of a container.  

![Screen Shot 2022-07-08 at 21 21 59](https://user-images.githubusercontent.com/12524453/178048999-adab7550-c542-431a-b7b1-38fc94e23814.png)

2022-07-08 18:29 UTC, wuletawwonte commented on README.md
> +# Portfolio Website
- [ ] Please add a description of the changes you made in this pull request in the details section of your pull request. When a description is added it's going to appear in the space pointed by the arrow in the following picture. 

![imageedit_4_3738492840](https://user-images.githubusercontent.com/12524453/178049853-2efe31d7-f6a0-4e64-9bfb-78b0a8bd1756.jpg)

2022-07-09 16:15 UTC, prolajumokeoni approved these changes
Hi @Blossom-Aniedi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 16:33 UTC, merged